sudo: required
dist: trusty

language: rust
rust: nightly

install:
  - chmod +x ci-install.sh && sh -C ci-install.sh

script:
  - make

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: elibot-apiserver
  skip_cleanup: true
  on:
    tags: true