sudo: required
dist: trusty

language: rust

rust: nightly

install:
  - chmod +x ci-install.sh && . ./ci-install.sh

script:
  - make

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: rustServer
  skip_cleanup: true
  on:
    tags: true